server:
  #  servlet:
  #    context-path: /context-path
  port: 8888

spring:
  application:
    name: redis-session
#  mvc:
#    servlet:
#      path: /path
  redis:
    host: localhost
    port: 6379
    password:
    database: 15
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        namespace:
      discovery:
        server-add: localhost:8848
    sentinel:
      enabled: true
      eager: true # 取消控制台懒加载，项目启动即连接Sentinel
      transport:
        port: 8082 # 本地客户端的端口
        dashboard: localhost:8081 # 控制台地址
      filter:
        enabled: false



