spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 15
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  session:
    redis:
      serializer: jackson
server:
  port: 8090


